apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs-k8s-web-deployment
  labels:
    app: vuejs-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vuejs-k8s-web-deployment
  template:
    metadata:
      labels:
        app: vuejs-k8s-web-deployment
    spec:
      containers:
      - name: vuejs-k8s-web
        image: registry.digitalocean.com/om-k8s/vuejs-k8s-web:latest
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "8080"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: om-k8s   


---
apiVersion: v1
kind: Service
metadata:
  name: vuejs-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: vuejs-k8s-web-deployment